import { registerAs } from '@nestjs/config';

export const configuration = registerAs('app', () => ({
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: Number(process.env.API_PORT ?? 4000),
  webOrigin: process.env.WEB_ORIGIN,
  databaseUrl: process.env.DATABASE_URL,
  redisUrl: process.env.REDIS_URL,
  stellarNetwork: process.env.STELLAR_NETWORK,
  stellarRpcUrl: process.env.STELLAR_RPC_URL,
  stablecoinPricesJson: process.env.STABLECOIN_PRICES_JSON,
  blendMainnetRpc: process.env.BLEND_MAINNET_RPC,
  blendMainnetPassphrase: process.env.BLEND_MAINNET_PASSPHRASE,
  blendMainnetPoolIdsJson: process.env.BLEND_MAINNET_POOL_IDS_JSON,
  blendTestnetRpc: process.env.BLEND_TESTNET_RPC,
  blendTestnetPassphrase: process.env.BLEND_TESTNET_PASSPHRASE,
  blendTestnetPoolIdsJson: process.env.BLEND_TESTNET_POOL_IDS_JSON,
  aquariusMainnetApi: process.env.AQUARIUS_MAINNET_API,
  aquariusMainnetRpc: process.env.AQUARIUS_MAINNET_RPC,
  aquariusMainnetPassphrase: process.env.AQUARIUS_MAINNET_PASSPHRASE,
  aquariusMainnetRouter: process.env.AQUARIUS_MAINNET_ROUTER,
  aquariusTestnetApi: process.env.AQUARIUS_TESTNET_API,
  aquariusTestnetRpc: process.env.AQUARIUS_TESTNET_RPC,
  aquariusTestnetPassphrase: process.env.AQUARIUS_TESTNET_PASSPHRASE,
  aquariusTestnetRouter: process.env.AQUARIUS_TESTNET_ROUTER,
  authChallengeTtlSeconds: Number(process.env.AUTH_CHALLENGE_TTL_SECONDS ?? 300),
  authSessionTtlSeconds: Number(process.env.AUTH_SESSION_TTL_SECONDS ?? 86400),
  anchorRequestTimeoutMs: Number(process.env.ANCHOR_REQUEST_TIMEOUT_MS ?? 8000),
  anchorStateTtlSeconds: Number(process.env.ANCHOR_STATE_TTL_SECONDS ?? 1800),
  crossChainProvider: process.env.CROSS_CHAIN_PROVIDER,
}));
