import Link from 'next/link';
import { Card, GlassPanel } from '../ui/design-system';
import { ProductVisualization } from './product-visualization';

const storySections = [{ id: 'product', eyebrow: 'The command center', title: 'See the whole financial picture.', body: 'One interface for assets, RWAs, DeFi, payments, yield, and cross-chain activity—organized around the way your capital actually moves.' }, { id: 'rwas', eyebrow: 'Real-world assets', title: 'Bring the real economy into view.', body: 'Track tokenized funds, stablecoins, and regulated financial products alongside the rest of your Stellar portfolio.' }, { id: 'defi', eyebrow: 'Open finance', title: 'Move from observation to action.', body: 'Understand protocol exposure, liquidity, lending, and yield with the context needed to make deliberate decisions.' }];

export function LandingHero() { return <section className="relative overflow-hidden px-5 pb-16 pt-28 sm:px-8 sm:pb-20 sm:pt-36"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_38%,hsl(var(--accent))/0.13,transparent_25%),radial-gradient(circle_at_40%_10%,hsl(var(--info))/0.08,transparent_28%)]" /><div className="relative mx-auto grid w-full max-w-7xl items-center gap-8 lg:grid-cols-[.9fr_1.1fr] lg:gap-4"><div className="max-w-2xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[hsl(var(--accent))]/20 bg-[hsl(var(--accent))]/[0.06] px-3 py-1.5 text-[10px] font-medium tracking-[0.14em] text-[hsl(var(--accent))]"><span className="h-1.5 w-1.5 rounded-full bg-[hsl(var(--positive))]" /> THE FINANCIAL COMMAND CENTER FOR STELLAR</div><h1 className="max-w-3xl text-5xl font-semibold leading-[1.02] tracking-[-0.05em] text-balance sm:text-6xl xl:text-7xl">One interface for your entire <span className="text-[hsl(var(--accent))]">on-chain financial life.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-[hsl(var(--muted))] sm:text-lg">Track assets, RWAs, DeFi positions, yields, payments and cross-chain activity without bouncing between fragmented applications.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/dashboard" className="inline-flex h-11 items-center justify-center rounded-md bg-[hsl(var(--accent))] px-5 text-sm font-semibold text-[hsl(var(--background))] hover:brightness-110">Launch Financial OS <span className="ml-2">→</span></Link><a href="#product" className="inline-flex h-11 items-center justify-center rounded-md border border-white/10 bg-white/[0.05] px-5 text-sm font-medium text-foreground hover:bg-white/[0.09]">Explore the Platform <span className="ml-2">↓</span></a></div><div className="mt-5 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-[hsl(var(--muted))]"><span>Non-custodial</span><span className="h-1 w-1 rounded-full bg-white/20" /><span>Wallet-signed</span><span className="h-1 w-1 rounded-full bg-white/20" /><span>Stellar-native</span></div></div><div className="relative lg:-mr-10"><ProductVisualization /></div></div></section>; }

export function LandingStory() { return <section id="product" className="mx-auto max-w-7xl space-y-24 px-5 py-24 sm:px-8 sm:py-32">{storySections.map((section, index) => <div id={section.id} key={section.id} className="grid gap-10 lg:grid-cols-2 lg:items-center"><div className={index % 2 === 1 ? 'lg:order-2' : ''}><p className="text-xs uppercase tracking-[0.16em] text-[hsl(var(--accent))]">{section.eyebrow}</p><h2 className="mt-4 max-w-lg text-3xl font-semibold tracking-tight sm:text-5xl">{section.title}</h2><p className="mt-5 max-w-lg text-base leading-7 text-[hsl(var(--muted))]">{section.body}</p></div><GlassPanel className={`min-h-64 overflow-hidden p-5 ${index % 2 === 1 ? 'lg:order-1' : ''}`}><div className="flex items-center justify-between border-b border-white/[0.08] pb-4"><span className="text-xs uppercase tracking-[0.14em] text-[hsl(var(--muted))]">Stellar OS / Preview</span><span className="h-2 w-2 rounded-full bg-[hsl(var(--accent))]" /></div><div className="mt-8 grid grid-cols-3 gap-3">{['Observe', 'Understand', 'Act'].map((label, itemIndex) => <div key={label} className="rounded-lg border border-white/[0.07] bg-white/[0.035] p-3"><div className={`h-16 rounded bg-gradient-to-br ${itemIndex === 1 ? 'from-[hsl(var(--accent))]/20' : 'from-white/[0.08]'} to-transparent`} /><p className="mt-3 text-xs text-[hsl(var(--muted))]">{label}</p></div>)}</div></GlassPanel></div>)}</section>; }

export function LandingClosing() { return <section id="security" className="px-5 pb-28 sm:px-8"><Card className="mx-auto max-w-7xl overflow-hidden p-8 sm:p-14"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs uppercase tracking-[0.16em] text-[hsl(var(--accent))]">A clearer financial future</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-tight sm:text-5xl">Your capital deserves a better vantage point.</h2><p className="mt-5 max-w-xl text-base leading-7 text-[hsl(var(--muted))]">Start with the account you already control. Stellar Financial OS keeps signing with your wallet and brings the system into focus.</p></div><Link href="/dashboard" className="inline-flex h-11 items-center justify-center rounded-md bg-[hsl(var(--accent))] px-5 text-sm font-semibold text-[hsl(var(--background))] hover:brightness-110">Enter Stellar OS →</Link></div></Card></section>; }
