import { Card, GlassPanel, StatusBadge } from '../ui/design-system';

const capabilities = [
  { id: 'portfolio', title: 'Unified Portfolio', body: 'Aggregate XLM, issued assets, contract tokens, and protocol positions into one normalized view with cost basis, allocation, and performance context.', tone: 'accent', className: 'lg:col-span-2' },
  { id: 'rwas', title: 'Real-World Assets', body: 'See BENJI-like funds, stablecoins, and tokenized financial products alongside native digital assets—with issuer and product metadata kept in view.', tone: 'positive', className: '' },
  { id: 'defi', title: 'DeFi', body: 'Track supplied, borrowed, and liquidity positions across Stellar protocols, including utilization, accrued rewards, and protocol exposure.', tone: 'info', className: '' },
  { id: 'payments', title: 'Payments', body: 'Follow transfers, anchor flows, and settlement activity from initiation to completion without leaving the account timeline.', tone: 'warning', className: '' },
  { id: 'risk', title: 'Risk', body: 'Surface concentration, liquidity, leverage, and health-ratio signals so you can understand portfolio risk before taking action.', tone: 'negative', className: '' },
  { id: 'cross-chain', title: 'Cross-chain', body: 'Monitor transfer state across networks, from source transaction through destination confirmation, in one activity model.', tone: 'accent', className: 'lg:col-span-2' },
] as const;

const toneMap = { accent: 'border-[hsl(var(--accent))]/20 bg-[hsl(var(--accent))]/[0.05]', positive: 'border-[hsl(var(--positive))]/20 bg-[hsl(var(--positive))]/[0.04]', info: 'border-[hsl(var(--info))]/20 bg-[hsl(var(--info))]/[0.04]', warning: 'border-[hsl(var(--warning))]/20 bg-[hsl(var(--warning))]/[0.04]', negative: 'border-[hsl(var(--negative))]/20 bg-[hsl(var(--negative))]/[0.04]' };

export function ProductOverview() { return <section id="platform" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="text-xs uppercase tracking-[0.16em] text-[hsl(var(--accent))]">The platform</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-6xl">One portfolio.<br />Every asset.<br />Every protocol.<br />Every payment.</h2></div><div className="max-w-lg lg:justify-self-end"><p className="text-base leading-7 text-[hsl(var(--muted))]">Stellar Financial OS turns a fragmented network into a legible operating surface. Each view is built around concrete decisions—not another dashboard full of disconnected numbers.</p><div className="mt-6 flex items-center gap-2"><StatusBadge tone="positive">Normalized data</StatusBadge><StatusBadge tone="accent">Wallet-signed</StatusBadge></div></div></div><div className="mt-16 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{capabilities.map((item, index) => <Card key={item.id} className={`${item.className} overflow-hidden p-6 ${toneMap[item.tone]}`}><div className="flex items-start justify-between"><span className="text-xs tabular-nums text-[hsl(var(--muted))]">0{index + 1}</span><span className="h-2 w-2 rounded-full bg-current opacity-70" /></div><h3 className="mt-12 text-xl font-semibold">{item.title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-[hsl(var(--muted))]">{item.body}</p>{item.id === 'portfolio' && <div className="mt-7 grid grid-cols-3 gap-2"><span className="h-12 rounded-md bg-[hsl(var(--accent))]/15" /><span className="h-12 rounded-md bg-[hsl(var(--accent))]/25" /><span className="h-12 rounded-md bg-[hsl(var(--accent))]/40" /></div>}{item.id === 'cross-chain' && <div className="mt-7 flex items-center gap-2 text-xs text-[hsl(var(--muted))]"><span className="rounded border border-white/10 px-2 py-1">Source</span><span className="text-[hsl(var(--accent))]">→</span><span className="rounded border border-white/10 px-2 py-1">Stellar OS</span><span className="text-[hsl(var(--accent))]">→</span><span className="rounded border border-white/10 px-2 py-1">Destination</span></div>}</Card>)}</div><GlassPanel className="mt-6 grid gap-6 p-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs uppercase tracking-[0.14em] text-[hsl(var(--muted))]">Built for clarity at network speed</p><p className="mt-3 max-w-2xl text-lg leading-7">From a wallet balance to a multi-protocol portfolio, the same operating model follows the capital—not the application that happens to hold the data.</p></div><div className="flex h-16 w-16 items-center justify-center rounded-full border border-[hsl(var(--accent))]/30 text-2xl text-[hsl(var(--accent))]">S</div></GlassPanel></section>; }
