import { Module } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  AccountBalance,
  AlertRule,
  Anchor,
  AnchorAsset,
  AnchorTransaction,
  Asset,
  AssetIssuer,
  AssetMetadata,
  AssetPrice,
  BorrowPosition,
  CrossChainTransfer,
  IndexerJob,
  LendingPosition,
  LiquidityPosition,
  Notification,
  Operation,
  Payment,
  PortfolioPosition,
  PortfolioSnapshot,
  Protocol,
  ProtocolMarket,
  ProtocolPosition,
  RewardPosition,
  RiskSnapshot,
  RwaMetadata,
  Session,
  StellarAccount,
  SyncCursor,
  Transaction,
  User,
  WalletConnection,
  WatchlistItem,
  YieldSnapshot,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      inject: [ConfigService],
      useFactory: (config: ConfigService) => ({
        type: 'postgres' as const,
        url: config.getOrThrow<string>('app.databaseUrl'),
        entities: [
          AccountBalance,
          AlertRule,
          Anchor,
          AnchorAsset,
          AnchorTransaction,
          Asset,
          AssetIssuer,
          AssetMetadata,
          AssetPrice,
          BorrowPosition,
          CrossChainTransfer,
          IndexerJob,
          LendingPosition,
          LiquidityPosition,
          Notification,
          Operation,
          Payment,
          PortfolioPosition,
          PortfolioSnapshot,
          Protocol,
          ProtocolMarket,
          ProtocolPosition,
          RewardPosition,
          RiskSnapshot,
          RwaMetadata,
          Session,
          StellarAccount,
          SyncCursor,
          Transaction,
          User,
          WalletConnection,
          WatchlistItem,
          YieldSnapshot,
        ],
        migrations: [__dirname + '/migrations/*{.ts,.js}'],
        migrationsRun: config.get<string>('app.nodeEnv') === 'production',
        synchronize: false,
        logging: config.get<string>('app.nodeEnv') === 'development' ? ['error'] : ['error'],
      }),
    }),
  ],
})
export class DatabaseModule {}
